from apt_select import apt as apt, argument as argument, constant as constant, mirror as mirror
from argparse import Namespace

def set_args() -> tuple[str | Namespace, int]: ...
def get_mirrors(mirrors_url: str, country: str, timeout_sec: float = ...) -> tuple[list[str], int]: ...
def print_status(info: dict[str, float | str], rank: int) -> None: ...
def print_latency(info: dict[str, float | str], rank: int, max_hostname_length: int) -> None: ...
def ask(query: str) -> str: ...
def get_selected_mirror(list_size: int) -> tuple[int | None, int]: ...
def yes_or_no(query: str) -> int: ...
def apt_select() -> tuple[str | None, int]: ...
def main() -> int: ...
