from _typeshed import Incomplete
from apt_select import utility as utility
from queue import Queue

PARSER: str

class ConnectError(Exception): ...

class Mirrors:
    urls: Incomplete
    got: Incomplete
    ranked: Incomplete
    top_list: Incomplete
    abort_launch: bool
    status_num: int
    def __init__(self, url_list: list[str], min_status: int, ping_only: bool | None = None) -> None: ...
    def fetch_launchpad_urls(self) -> None: ...
    def measure_rtts(self) -> None: ...
    def lookup_statuses(self, codename: str, arch: str) -> None: ...

class _RoundTrip:
    def __init__(self, url: str, host: str, trip_queue: Queue[tuple[str, float] | None]) -> None: ...
    def min_rtt(self) -> None: ...

class _LaunchData:
    def __init__(self, url: str, launch_url: str, codename: str, arch: str, data_queue: Queue[tuple[str, dict[str, str] | None]]) -> None: ...
    def get_info(self) -> None: ...
