DEFAULT_REQUEST_HEADERS = {"User-Agent": "apt-select"}
DEFAULT_REQUEST_TIMEOUT_SEC = 120.0
ENCODING_UTF_8 = "utf-8"

OK = 0
NOK = 1
INVALID_MIRROR_INDEX = 2
USER_INTERRUPT = 3
SKIPPED_FILE_GENERATION = 4
